lesson_08/blog/post/views.py
import os

from flask import Blueprint, render_template, request, redirect, url_for, current_app
from flask_login import login_required, current_user

from blog.extension import db
from blog.forms.post_forms import CreatePostForm, CommentForm
from blog.functions import render_with_common_dict, get_file_name
from blog.models import User, Profile, Post, Category, Tag, Like

post = Blueprint("post", __name__, static_folder="../static")


@post.route("/", methods=('GET',))
@post.route('/index', methods=('GET',))
def post_list():
    return render_with_common_dict("post/posts.html", posts=Post.query.all())


@post.route("/<int:pk>", methods=('GET',))
def post_detail(pk: int):
    form = CommentForm()
    if request.args.get('like', ''):
        if current_user.is_authenticated:
            # проверка user, post -> 1 like
            if not Like.query.filter_by(post_id=pk, user_id=current_user.id).all():
                like = Like(post_id=pk, user_id=current_user.id)
                db.session.add(like)
                db.session.commit()
    return render_with_common_dict("post/post_detail.html", post=Post.query.get(pk), form=form)


@post.route("/tag/<int:pk>", methods=('GET',))
def posts_by_tag(pk: int):
    return render_with_common_dict("post/posts.html", posts=Tag.query.get(pk).posts)


@post.route("/ctg/<int:pk>", methods=('GET',))
def posts_by_category(pk: int):
    return render_with_common_dict("post/posts.html", posts=Category.query.get(pk).posts)


@post.route("/create", methods=('GET', 'POST'))
@login_required
def create_post():
    form = CreatePostForm(request.form)
    if request.method == "GET":
        return render_with_common_dict("post/create_post.html", form=form)
    if form.validate_on_submit():
        title = form.title.data.strip()
        content = form.content.data
        category = Category.query.get(int(form.category.data))
        file_name = None
        if f := form.photo.data:
            f.save(os.path.join(current_app.config['UPLOAD_FOLDER'], get_file_name(f.filename)))
        author = User.query.get(current_user.id)
        tags = [tag for tag in Tag.query.filter(Tag.id.in_(form.tags.data))]
        cur_post = Post(title=title, image=file_name, content=content, category=category, author=author, tags=tags)
        db.session.add(cur_post)
        db.session.commit()
        return redirect(url_for('post.post_list'))
    return render_with_common_dict("post/create_post.html", form=form)

lesson_08/blog/user/views.py
from flask import Blueprint, render_template
from werkzeug.exceptions import NotFound

from blog.functions import render_with_common_dict
from blog.models import User

user = Blueprint("user", __name__, url_prefix="/users", static_folder="../static")


@user.route("/")
def user_list():
    return render_with_common_dict("user/users.html", users=User.query.all())


@user.route("/<int:pk>")
def user_detail(pk: int):
    return render_with_common_dict("user/user_detail.html", user=User.query.get(pk))

lesson_08/blog/templates/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('post.post_list') }}">
      <b>Новостной блог</b>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-1 mb-lg-0 top-menu">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{{ url_for('post.post_list') }}">Посты</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{{ url_for('post.create_post') }}">Создать пост</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{{ url_for('user.user_list') }}">Пользователи</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="/admin">Админ-панель</a>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto mb-1 mb-lg-0">
        <li class="nav-item">
          {% if current_user.is_authenticated %}
          <label class="font-light pe-3 pt-2">Привет, {{ current_user.login }}! </label>
          {% else %}
          <label class="font-light  pe-3 pt-2">Зарегистрируйтесь!</label>
          {% endif %}
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#">
            <i class="fa-regular fa-user" style="color: #000000;"></i>
          </a>
          <ul class="dropdown-menu">
            {% if current_user.is_authenticated %}
            <li><a class="dropdown-item" href="{{ url_for('auth.logout') }}">Выход</a></li>
            {% else %}
            <li><a class="dropdown-item" href="{{ url_for('auth.login') }}">Авторизация</a></li>
            <li><a class="dropdown-item" href="{{ url_for('auth.register') }}">Регистрация</a></li>
            {% endif %}

          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

lesson_08/blog/templates/_right.html
<br>
<form class="form-search">
  <input type="text" class="input-medium search-query">
  <button type="submit" class="btn"><i class="fas fa-search"></i></button>
</form>
<br>

<p class="sidebar-head my-3">Категории</p>
<ul class="list-group list-group-flush mx-2">
  {% for category in categories %}
  <li class="list-group-item d-flex justify-content-between align-items-start">
    <div class="ms-2 me-auto">
      <a class="ctgs" href="{{ url_for('post.posts_by_category', pk=category.id) }}">{{ category.name }}</a>
    </div>
    <span class="badge rounded-pill">{{ category.posts|length }}</span>
  </li>
  {% endfor %}
</ul>

<p class="sidebar-head my-3">Топ просмотров</p>

<p class="sidebar-head my-3">Облако тегов</p>
{% for tag in tags %}
<a type="button" href="{{ url_for('post.posts_by_tag', pk=tag.id) }}" class="btn btn-outline-secondary my-1">
  {{ tag.title }}
</a>
{% endfor %}

lesson_08/blog/templates/base.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}Новостной портал {% endblock %}</title>
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  <!-- Font Lora 400, Roboto Light 300, Regular 400, Medium 500, Bold 700 -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Lora&family=Roboto:wght@300;400;500;700&display=swap"
        rel="stylesheet">
  <!-- Set up Font Awesome Kit -->
  <script src="https://kit.fontawesome.com/f2dcb0d7c6.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="/static/css/style.css">
</head>

<body>
<div class="parent-container">

  <header class="header">
    {% block navbar %}{% include "_navbar.html" %}{% endblock %}
  </header>

  <div class="title">
    <div class="pt-3 pageheader-section">
      <h3>{% block page_title %}{% endblock %}</h3>
    </div>
  </div>

  <main class="main mx-4">
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-danger" role="alert">
      {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
    {% block content %}{% endblock %}
  </main>

  <aside class="right">
    {% block sidebar %}{% include "_right.html" %}{% endblock %}
  </aside>

  <footer class="footer">
    @Copyright
  </footer>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
</body>

</html>