lesson_02/blog/app.py
from flask import Flask

from blog.article.views import article
from blog.user.views import user


def create_app() -> Flask:
    app = Flask(__name__)
    [app.register_blueprint(bp) for bp in (user, article)]  # register Blueprints
    return app

lesson_02/blog/article/views.py
from flask import Blueprint, render_template
from werkzeug.exceptions import NotFound

from blog.data import articles, get_users_by_id, get_article_by_id, get_user_by_id

article = Blueprint("article", __name__, url_prefix="", static_folder="../static")


@article.route("/")
def article_list():
    return render_template("article/articles.html", articles=articles, users_by_id=get_users_by_id())


@article.route("/<int:pk>")
def article_detail(pk: int):
    art = get_article_by_id(pk)
    user = get_user_by_id(art.get('author_id'))
    if art and user:
        return render_template("article/article_detail.html", article=art, user=user)
    raise NotFound(f"Не существует автора с id:{art.get('author_id')} или статьи с id:{pk}!")

lesson_02/blog/user/views.py
from flask import Blueprint, render_template
from werkzeug.exceptions import NotFound

from blog.data import users

user = Blueprint("user", __name__, url_prefix="/users", static_folder="../static")


@user.route("/")
def user_list():
    return render_template("user/users.html", users=users)


# @user.route("/<int:pk>")
# def get_user(pk: int):
#     if pk in USERS:
#         user_raw = USERS[pk]
#     else:
#         raise NotFound("User id:{}, not found".format(pk))
#     return render_template(
#         "users/details.html",
#         user_name=user_raw["name"]
#     )

#
# def get_user_name(pk: int):
#     if pk in USERS:
#         user_name = USERS[pk]["name"]
#     else:
#         raise NotFound("User id:{}, not found".format(pk))
#     return user_name

lesson_02/blog/templates/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('article.article_list') }}">
      <b>Новостной блог</b>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-1 mb-lg-0 top-menu">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{{ url_for('article.article_list') }}">Статьи</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{{ url_for('user.user_list') }}">Пользователи</a>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto mb-1 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="">
            <i class="fa-solid fa-magnifying-glass" style="color: #000000;"></i>
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#">
            <i class="fa-regular fa-user" style="color: #000000;"></i>
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Регистрация</a></li>
            <li><a class="dropdown-item" href="#">Авторизация</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

lesson_02/blog/templates/base.html
<!doctype html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}Новостной портал {% endblock %}</title>
	<!-- Bootstrap CSS -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
	<!-- Font Lora 400, Roboto Light 300, Regular 400, Medium 500, Bold 700 -->
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Lora&family=Roboto:wght@300;400;500;700&display=swap"
		rel="stylesheet">
	<!-- Set up Font Awesome Kit -->
	<script src="https://kit.fontawesome.com/f2dcb0d7c6.js" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="static/css/style.css">
</head>

<body>
	<div class="parent-container">

		<header class="header">
			{% block navbar %}{% include "_navbar.html" %}{% endblock %}
		</header>

		<main class="main mx-4">
			<div class="mt-5 pageheader-section">
				<h3>{% block page_title %}{% endblock %}</h3>
			</div>
			{% block content %}{% endblock %}
		</main>

		<aside class="right">
			{% block sidebar %}{% include "_right.html" %}{% endblock %}
		</aside>

		<footer class="footer">
			@Copyright
		</footer>
	</div>

	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
		integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
		crossorigin="anonymous"></script>
</body>

</html>