lesson_07/blog/models.py
from datetime import datetime

from flask_login import UserMixin

from blog.extension import db, login_manager


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(db.Model, UserMixin):
    """ Пользователь """
    id = db.Column(db.Integer(), primary_key=True)
    login = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(500), nullable=False)
    is_staff = db.Column(db.Boolean, default=False)

    profile = db.relationship('Profile', back_populates='user', uselist=False, cascade="all, delete")
    post = db.relationship('Post', back_populates='author', cascade="all, delete")

    def __repr__(self):
        return f"<User id={self.id} {self.login}>"


class Profile(db.Model):
    """ Профиль пользователя (связь с User 1:1) """
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(), nullable=False)
    email = db.Column(db.String(), unique=True)
    birthday = db.Column(db.DateTime, nullable=True)
    created = db.Column(db.String(), default=datetime.utcnow)
    user_id = db.Column(db.Integer(), db.ForeignKey('user.id', ondelete="CASCADE"))

    user = db.relationship('User', back_populates='profile')

    def __repr__(self):
        return f"<Profile {self.id} of user {self.user_id}>"


class Category(db.Model):
    """ Категория поста (связь с Post 1:М) """
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(), nullable=False)

    posts = db.relationship('Post', back_populates='category')

    def __repr__(self):
        return f"<{self.name}>"


post_tag = db.Table('post_tag', db.metadata,
                    db.Column('tag_id', db.Integer, db.ForeignKey('tag.id')),
                    db.Column('post_id', db.Integer, db.ForeignKey('post.id')))


class Post(db.Model):
    """ Post: связь с User 1:M; связь с Category 1:М; связь с Tag M:М) """
    id = db.Column(db.Integer(), primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    image = db.Column(db.String(200), nullable=True)
    content = db.Column(db.Text(), nullable=True)
    created = db.Column(db.DateTime, default=datetime.utcnow)
    updated = db.Column(db.DateTime)
    draft = db.Column(db.Boolean, default=False)
    user_id = db.Column(db.Integer(), db.ForeignKey('user.id', ondelete="CASCADE"))
    category_id = db.Column(db.Integer(), db.ForeignKey('category.id', ondelete="CASCADE"))

    author = db.relationship('User', back_populates='post')
    category = db.relationship('Category', back_populates='posts')

    tags = db.relationship('Tag', secondary=post_tag, back_populates='posts')

    def __repr__(self):
        return f"<Post id={self.id} {self.title}>"


class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100))
    posts = db.relationship('Post', secondary=post_tag, back_populates='tags')

    def __repr__(self):
        return f"<Tag {self.title}>"

lesson_07/blog/forms/post_forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed, FileRequired
from wtforms import StringField, validators, SubmitField, TextAreaField, SelectField, SelectMultipleField

from blog.models import Category, Tag


class CreatePostForm(FlaskForm):
    title = StringField('Заголовок поста', [validators.Length(min=1, message='Поле "Заголовок" требует заполнения')])
    content = TextAreaField('Содержание поста', render_kw=dict(rows="9", cols="25"))
    category = SelectField('Выберите категорию поста')
    photo = FileField(validators=[FileAllowed(["png", "jpg", "jpeg", "webp", "gif"], "Тип файла не разрешен!", )], )
    tags = SelectMultipleField('Выберите теги', coerce=int)
    submit = SubmitField('Создать')
    fields = ['title', 'content', 'category', 'photo', 'tags', 'submit']

    def __init__(self, *args, **kwargs):
        super(CreatePostForm, self).__init__(*args, **kwargs)
        self.category.choices = [(ctg.id, ctg.name) for ctg in Category.query.all()]
        self.tags.choices = [(tag.id, tag.title) for tag in Tag.query.all()]

lesson_07/blog/__init__.py
from flask import Flask

from blog import config, extension


def create_app() -> Flask:
    app = Flask(__name__)
    app.config.from_object(config.DevConfig)  # environment: BaseConfig, DevConfig, TestConfig
    print(app.config)
    register_extensions(app)  # register db
    register_blueprints(app)  # register Blueprints
    # register_commands(app)  # register console commands
    return app


def register_extensions(app: Flask):
    extension.db.init_app(app)

    extension.migrate.init_app(app, extension.db, compare_type=True)

    extension.login_manager.login_view = 'auth.login'
    extension.login_manager.init_app(app)


def register_blueprints(app: Flask):
    """ Регистрация блюпринтов """
    from blog.auth.views import auth
    from blog.post.views import post
    from blog.user.views import user
    [app.register_blueprint(bp) for bp in (user, post, auth)]

lesson_07/blog/post/views.py
import os
from secrets import token_hex

from flask import Blueprint, render_template, request, redirect, url_for, current_app
from flask_login import login_required, current_user
from PIL import Image
from werkzeug.exceptions import NotFound
from werkzeug.utils import secure_filename

from blog.extension import db
from blog.forms.post_forms import CreatePostForm
from blog.functions import render_with_common_dict
from blog.models import User, Profile, Post, Category, Tag

post = Blueprint("post", __name__, static_folder="../static")


@post.route("/", methods=('GET',))
@post.route('/index', methods=('GET',))
def post_list():
    return render_with_common_dict("post/posts.html", posts=Post.query.all())


@post.route("/<int:pk>", methods=('GET',))
def post_detail(pk: int):
    return render_with_common_dict("post/post_detail.html", post=Post.query.get(pk))


@post.route("/tag/<int:pk>", methods=('GET',))
def posts_by_tag(pk: int):
    return render_with_common_dict("post/posts.html", posts=Tag.query.get(pk).posts)


@post.route("/ctg/<int:pk>", methods=('GET',))
def posts_by_category(pk: int):
    return render_with_common_dict("post/posts.html", posts=Category.query.get(pk).posts)


@post.route("/create", methods=('GET', 'POST'))
@login_required
def create_post():
    form = CreatePostForm(request.form)
    if request.method == "GET":
        return render_with_common_dict("post/create_post.html", form=form)
    if form.validate_on_submit():
        title = form.title.data.strip()
        content = form.content.data
        category = Category.query.get(int(form.category.data))
        file_name = None
        if img_file := form.photo.data:
            f_name, f_ext = os.path.splitext(secure_filename(img_file.filename))
            file_name = f"{f_name}_{token_hex(8)}{f_ext}"
            img_file.save(os.path.join(current_app.config['UPLOAD_FOLDER'], file_name))
        author = User.query.get(current_user.id)
        tags = [tag for tag in Tag.query.filter(Tag.id.in_(form.tags.data))]
        cur_post = Post(title=title, image=file_name, content=content, category=category, author=author, tags=tags)
        db.session.add(cur_post)
        db.session.commit()
        return redirect(url_for('post.post_list'))
    return render_with_common_dict("post/create_post.html", form=form)

lesson_07/blog/templates/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('post.post_list') }}">
      <b>Новостной блог</b>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-1 mb-lg-0 top-menu">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{{ url_for('post.post_list') }}">Посты</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{{ url_for('post.create_post') }}">Создать пост</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{{ url_for('user.user_list') }}">Пользователи</a>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto mb-1 mb-lg-0">
        <li class="nav-item">
          {% if current_user.is_authenticated %}
          <label class="font-light pe-3 pt-2">Привет, {{ current_user.login }}! </label>
          {% else %}
          <label class="font-light  pe-3 pt-2">Зарегистрируйтесь!</label>
          {% endif %}
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#">
            <i class="fa-regular fa-user" style="color: #000000;"></i>
          </a>
          <ul class="dropdown-menu">
            {% if current_user.is_authenticated %}
            <li><a class="dropdown-item" href="{{ url_for('auth.logout') }}">Выход</a></li>
            {% else %}
            <li><a class="dropdown-item" href="{{ url_for('auth.login') }}">Авторизация</a></li>
            <li><a class="dropdown-item" href="{{ url_for('auth.register') }}">Регистрация</a></li>
            {% endif %}

          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

lesson_07/blog/templates/_right.html
<br>
<form class="form-search">
  <input type="text" class="input-medium search-query">
  <button type="submit" class="btn"><i class="fas fa-search"></i></button>
</form>
<br>

<p class="sidebar-head my-3">Категории</p>
<ul class="list-group list-group-flush mx-2">
  {% for category, num in cats %}
  <li class="list-group-item d-flex justify-content-between align-items-start">
    <div class="ms-2 me-auto">
      <a class="ctgs" href="{{ url_for('post.posts_by_category', pk=category.id) }}">{{ category.name }}</a>
    </div>
    <span class="badge rounded-pill">{{ num }}</span>
  </li>
  {% endfor %}
</ul>

<p class="sidebar-head my-3">Топ просмотров</p>

<p class="sidebar-head my-3">Облако тегов</p>
{% for tag in tags %}
<a type="button" href="{{ url_for('post.posts_by_tag', pk=tag.id) }}" class="btn btn-outline-secondary my-1">
  {{ tag.title }}
</a>
{% endfor %}

lesson_07/blog/templates/post/post_detail.html
{% extends 'base.html' %}
<body>
{% block content %}
<div class="post-card">
  <div class="art-details">
    <div class="my-4">
      <h5>{{ post.title }}</h5>
    </div>
    <div class="my-4">
      <img src="static/img/post/no_photo.webp" class="img-fluid rounded-start" alt="...">
    </div>
    <p>{{ post.content }}</p>
    <div class="product-bottom-details d-flex justify-content-between">
      <div class="product-price">
        <div class="post-meta">
          <span><i class="fa-solid fa-tags"></i> Теги: </span>
          {% for tag in post.tags%}
          <span><a href="{{ url_for('post.posts_by_tag', pk=tag.id) }}">{{ tag.title }}</a></span>
          {% if not loop.last %}
          <span>•</span>
          {% endif %}
          {% endfor%}
        </div>
        <div class="post-meta">
          <span><i class="fa-regular fa-circle-user"></i> {{ post.author.profile.name }}</span>
          <span>•</span>
          <span><i class="fa-regular fa-calendar"></i> {{ post.created }}</span>
          <span>•</span>
          <span><a href="{{ url_for('post.posts_by_category', pk=post.category_id) }}">
            <i class="fa-regular fa-folder-open"></i> {{post.category.name}}</a></span>
          <span>•</span>
          <span><i class="fa-regular fa-comments"></i> 5</span>
        </div>
      </div>
      <div class="comment-links">
        <a href="#"><i class="fa-regular fa-comments"></i></a>
        <a href="#"><i class="far fa-heart"></i></a>
      </div>
    </div>
  </div>
</div>

{% endblock %}
</body>
</html>

lesson_07/blog/templates/post/posts.html
{% extends 'base.html' %}
<body>
{% block page_title %}Список постов{% endblock %}
{% block content %}
{% for post in posts %}
<div class="col-lg-12 col-sm-6 mb-3">
  <div class="row g-0 post-card">
    <div class="col-md-2 post-thumb">
      <img src="/static/img/post/no_photo.webp" class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-10 post-details">
      <h5><a href="{{ url_for('post.post_detail', pk=post.id) }}">{{ post.title }}</a></h5>
      <div class="post-meta">
        <span><i class="fa-solid fa-tags"></i> Теги: </span>
        {% for tag in post.tags%}
          <span><a href="{{ url_for('post.posts_by_tag', pk=tag.id) }}">{{ tag.title }}</a></span>
            {% if not loop.last %}
            <span>•</span>
            {% endif %}
        {% endfor%}
      </div>
      <div class="post-meta">
        <span><i class="fa-regular fa-circle-user"></i> {{ post.author.profile.name }}</span>
        <span>•</span>
        <span><i class="fa-regular fa-calendar"></i> {{ post.created }}</span>
        <span>•</span>
        <span><a href="{{ url_for('post.posts_by_category', pk=post.category_id) }}">
          <i class="fa-regular fa-folder-open"></i> {{post.category.name}}</a></span>
        <span>•</span>
        <span><i class="fa-regular fa-comments"></i> 5</span>
      </div>
      <p>{{ post.content }}</p>
      <a href="{{ url_for('post.post_detail', pk=post.id) }}" class="post-btn">
        Читать далее >
      </a>
    </div>
  </div>
</div>
{% endfor %}
{% endblock %}
</body>
</html>