lesson_05/blog/models.py
from datetime import datetime

from flask_login import UserMixin

from blog.extension import db


class User(db.Model, UserMixin):
    """ Пользователь """
    id = db.Column(db.Integer(), primary_key=True)
    login = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(500), nullable=False)
    is_staff = db.Column(db.Boolean, default=False)

    profile = db.relationship('Profile', back_populates='user', uselist=False, cascade="all, delete")
    post = db.relationship('Post', back_populates='author', cascade="all, delete")

    def __repr__(self):
        return f"<User id={self.id} {self.login}>"


class Profile(db.Model):
    """ Профиль пользователя (связь с User 1:1) """
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(), nullable=False)
    email = db.Column(db.String(), unique=True)
    birthday = db.Column(db.DateTime, nullable=True)
    created = db.Column(db.String(), default=datetime.utcnow)
    user_id = db.Column(db.Integer(), db.ForeignKey('user.id', ondelete="CASCADE"))

    user = db.relationship('User', back_populates='profile')

    def __repr__(self):
        return f"<Profile {self.id} of user {self.user_id}>"


class Category(db.Model):
    """ Категория поста (связь с Post 1:М) """
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(), nullable=False)

    post = db.relationship('Post', back_populates='category')

    def __repr__(self):
        return f"<Profile {self.id} of user {self.user_id}>"


class Post(db.Model):
    """ Пост (связь с User 1:М; связь с Category 1:М) """
    id = db.Column(db.Integer(), primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    content = db.Column(db.Text(), nullable=True)
    photo = db.Column(db.String(200), nullable=True)
    created = db.Column(db.DateTime, default=datetime.utcnow)
    updated = db.Column(db.DateTime)
    draft = db.Column(db.Boolean, default=False)
    user_id = db.Column(db.Integer(), db.ForeignKey('user.id', ondelete="CASCADE"))
    category_id = db.Column(db.Integer(), db.ForeignKey('category.id', ondelete="CASCADE"))

    author = db.relationship('User', back_populates='post')
    category = db.relationship('Category', back_populates='post')

    def __repr__(self):
        return f"<Post id={self.id} {self.title}>"

lesson_05/blog/forms/user_forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, validators, SubmitField, PasswordField


class UserLoginForm(FlaskForm):
    login = StringField("Логин", [validators.DataRequired(), ])
    password = PasswordField("Пароль", [validators.DataRequired(), ])
    submit = SubmitField('Авторизоваться')


class UserRegisterForm(FlaskForm):
    login = StringField("Логин", [validators.DataRequired(), ])
    name = StringField("Полное имя", [validators.DataRequired(), ])
    email = StringField("Е-мейл", [validators.DataRequired(), validators.Email()], )
    password = PasswordField("Пароль", [validators.DataRequired(), validators.EqualTo("confirm")], )
    confirm = PasswordField("Подтверждение пароля", [validators.DataRequired(), ])
    submit = SubmitField('Зарегистрироваться')

lesson_05/blog/post/views.py
from flask import Blueprint, render_template
from werkzeug.exceptions import NotFound

from blog.models import User, Profile, Post, Category

post = Blueprint("post", __name__, static_folder="../static")


@post.route("/")
def post_list():
    return render_template("post/posts.html", posts=Post.query.all())


@post.route("/<int:pk>")
def post_detail(pk: int):
    return render_template("post/post_detail.html", post=Post.query.get(pk))

lesson_05/blog/templates/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('post.post_list') }}">
      <b>Новостной блог</b>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-1 mb-lg-0 top-menu">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{{ url_for('post.post_list') }}">Статьи</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{{ url_for('user.user_list') }}">Пользователи</a>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto mb-1 mb-lg-0">
        <li class="nav-item">
          {% if current_user.is_authenticated %}
          <label class="font-light pe-3 pt-2">Привет, {{ current_user.login }}! </label>
          {% else %}
          <label class="font-light  pe-3 pt-2">Зарегистрируйтесь!</label>
          {% endif %}
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#">
            <i class="fa-regular fa-user" style="color: #000000;"></i>
          </a>
          <ul class="dropdown-menu">
            {% if current_user.is_authenticated %}
            <li><a class="dropdown-item" href="{{ url_for('auth.logout') }}">Логаут</a></li>
            {% else %}
            <li><a class="dropdown-item" href="{{ url_for('auth.login') }}">Авторизация</a></li>
            <li><a class="dropdown-item" href="{{ url_for('auth.register') }}">Регистрация</a></li>
            {% endif %}

          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>